### PR TITLE
Extracted plural processing to new class CommandUtils

### PR DESCRIPTION
**Pull request by jotadepicas**
Hi Bruno,
I've created a new class [CommandUtils](https://github.com/jotadepicas/annabell/blob/master/src/CommandUtils.h) to begin extracting string processing outside annabell_main. 
As a first step and example, I've extracted just the plural suffix processing.

One comment: I haven't updated src/Makefile.am to add CommandUtils.h because everything seems to be compiling without doing so, let me know if you get any compile errors (and sorry in advance if you do :/)

Also, I've started a repo for creating Unit Tests, to ensure everything keeps working as expected. Have a look at [annabell-tests](https://github.com/jotadepicas/annabell-tests).

I think this tests should be a part of your main repo, because otherwise they will be inevitably outdated if someone changes the code without updating the tests. Moreover, running tests could be enforced in the make of the project. But for this, I think the main repo structure should be changed, so the root directory contains both projects (annabell and annabell-tests).

Let me know what you think, or if you have any trouble running the tests.

best,
-Juan

### CODE REVIEW

**Comment by golosio** [comment]
Excellent, thank you Juan, and BTW happy new year!
Everything seems to be fine for me with compiling. I think it is not necessary to include the header file in the Makefile.am
I'll try to install and run annabell-tests as soon as I can.
best, Bruno

**Comment by jotadepicas** [comment]
Happy new year to you too! Regarding the tests let me know if you encounter any problems.

**Comment by golosio** [comment]
On linux I was able to compile the test via command line: 
g++ -I ../../annabell/src/ -o annabell-test ParseCommandTests.cpp -lgtest -lpthread
and it seems to run properly. Let me know if I should compile it in a different way.

**Comment by jotadepicas** [comment]
I think that looks OK, you are referencing both annabell/src and the GoogleTest libraries.
Were you able to run the tests main? It should give a console output similar to this:

```
[==========] Running 1 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 1 tests from CommandUtilsTests
[ RUN      ] CommandUtilsTests.pluralTest
[       OK ] CommandUtilsTests.pluralTest (0 ms)
[----------] 1 tests from CommandUtilsTests (0 ms total)

[----------] Global test environment tear-down
[==========] 1 tests from 1 test case ran. (5 ms total)
[  PASSED  ] 1 tests.
```

**Comment by golosio** [comment]
Yes, I got exactly this output.

**Comment by jotadepicas** [comment]
Excellent, so everything is working as expected. From now on, whenever a refactor is made or feature is added, the corresponding tests could be added too. These first tests are trivial of course, but more interesting things could be done. We could write tests for all the expected behavior for the cross validation files and other things like that.
  
I'll add how you compiled it to the tests build instructions for linux platform, thanks!

**Pull request merged**
